baseURL = "/"
languageCode = "en-us"
title = "Benjamin Hill"
theme = "kube"
description = "A website by Benjamin Hill, showcasing completed works, resume, and contact information"
Paginate = 4
enableRobotsTXT = true
canonifyURLs = true
pygmentsStyle = "github"
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = true

[Params]
  RSSLink = "/index.xml"
  author = "Benjamin Hill" # add your company name
  github = "https://github.com/Benjamin00/" # add your github profile name
  twitter = "" # add your twitter profile
  email = "BenjaminHillCS@gmail.com"

[[menu.main]]
    name = "Portfolio"
    weight = -100
    url = "/portfolio/"
[[menu.main]]
    name = "Background"
    weight = -100
    url = "/background/"
[[menu.main]]
    name = "Resume"
    weight = -100
    url = "/resume/"
[[menu.main]]
    name = "Devlog"
    weight = -50
    url = "/blog/"

[markup]
   [markup.goldmark]     
      [markup.goldmark.renderer]        
         unsafe = true
         
[Params.seo.webmaster_verifications]
  google = "google-site-verification=IwKwQtHChs30NyRUkx9XXRwvR4J1_Y8Gm0i82Ylgens"
